### ISSUE TITLE
Cannot change the screen resolution

### ISSUE THREAD

**Issue by Kongsea** [floydhub/dl-setup#2]
I meet some problems after I install the Ubuntu 14.04.

My computer is a 64-bit one with a NVIDIA TITAN X GPU. After I install the Ubuntu 14.04 and the NVIDIA 361.42 GPU driver, I cannot change the screen resolution. The only resolutions are 640\* and 380*. Anyone can help me?

Thanks.

**Comment by saiprashanths** [comment]
It is likely that the drivers are not installed correctly. What do you see with `cat /proc/driver/nvidia/version`? Also did you install the drivers directly from Nvidia's site or from the PPA in the guide?

**Comment by Kongsea** [comment]
Actually, after executing the code you mentioned, I definitely can see the correct GPU driver installed.
And the driver was also downloaded from Nvidia's site.
However, I still cannot change the resolution.
At last, I solve the problem by installing CUDA instead of installing the driver first because I found CUDA containes the GPU driver.
Anyway, thank you very much.
