### ISSUE TITLE
Have to add Caffe to my environment variable every login.

### ISSUE THREAD

**Issue by Rich700000000000** [floydhub/dl-setup#3]
I can't import caffe (in python 2.7) unless I navigate to git/caffe and re-run 

```
echo 'export CAFFE_ROOT=$(pwd)' >> ~/.bashrc
echo 'export PYTHONPATH=$CAFFE_ROOT/python:$PYTHONPATH' >> ~/.bashrc
source ~/.bashrc
```

over and over. Caffe _works_, but not until I do that.

How can I fix this?

**Comment by Rich700000000000** [comment]
Wait, what happened?

**Comment by saiprashanths** [comment]
Take a look at http://stackoverflow.com/questions/820517/bashrc-at-ssh-login. Are you using SSH? Either way, SO might be a better place for this. No Linux expert myself :)

**Comment by wlrider** [comment]
I am having the same issue- was a solution ever found?

EDIT: I should have continued working before posting a question BUT I figured out the problem. 
The path was wrong in /.bashrc

   -Not working = export CAFFE_ROOT=$(pwd)
                           export PYTHONPATH=$CAFFE_ROOT/python:$PYTHONPATH
   
-Working =  export CAFFE_ROOT=$(pwd)
                       export PYTHONPATH=/home/lee/git/caffe/python:$PYTHONPATH
